- hosts: localhost
  gather_facts: false
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  vars_files:
    - resources.yml
  tasks:
    - gravesm.eda.resources:
        state: "{{ state | default('present') }}"
